name: Setup Node.js and cache dependencies

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
        description: "The Node.js version to use"
      cache-key:
        required: true
        type: string
        description: "The key used for caching node_modules"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ inputs.cache-key }}